<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Property;
use App\Models\User;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        // 1. Setup User Admin (Aman, tidak menimpa jika sudah ada)
        $user = User::firstOrCreate(
            ['email' => 'admin@roov.com'],
            ['name' => 'Admin Roov', 'password' => Hash::make('password123')]
        );

        // 2. Data 12 Properti Bervariasi
        $properties = [
            // --- KATEGORI: RUMAH SULTAN (LUXURY) ---
            [
                'title' => 'Rumah Sultan Classic Hook Pakuwon City',
                'description' => "Rumah mewah gaya klasik mediterania di cluster paling elite. Posisi Hook dengan taman samping luas dan kolam renang pribadi.\n\nFasilitas:\n- Private Pool & Jacuzzi\n- Full Marmer Import Italy\n- Ruang Karaoke Kedap Suara",
                'price' => 18500000000,
                'listing_type' => 'secondary',
                'property_type' => 'rumah',
                'bedrooms' => 5,
                'maid_bedrooms' => 2,
                'bathrooms' => 5,
                'maid_bathrooms' => 1,
                'land_area' => 450,
                'building_area' => 700,
                'floor_count' => 2,
                'certificate' => 'SHM',
                'electricity' => 13000,
                'orientation' => 'Utara',
                'furnishing' => 'Full Furnished',
                'water_source' => 'PDAM',
                'garage_size' => 2,
                'carport_size' => 2,
                'is_hook' => true,
                'has_canopy' => false,
                'has_smart_home' => true,
                'has_fence' => true,
                'has_pool' => true,
                'has_carport' => true,
                'has_garden' => true,
                'city' => 'Surabaya',
                'district' => 'Mulyorejo',
                'address' => 'Grand Island Cluster San Diego',
                'photo' => 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop',
                'gallery' => ['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=1200', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200'],
            ],
            [
                'title' => 'Modern Tropical House di Graha Famili',
                'description' => "Hunian modern tropical dengan view lapangan golf. Desain arsitek ternama, sirkulasi udara sangat baik.",
                'price' => 25000000000,
                'listing_type' => 'secondary',
                'property_type' => 'rumah',
                'bedrooms' => 6,
                'maid_bedrooms' => 2,
                'bathrooms' => 6,
                'maid_bathrooms' => 1,
                'land_area' => 600,
                'building_area' => 900,
                'floor_count' => 3,
                'certificate' => 'SHM',
                'electricity' => 22000,
                'orientation' => 'Timur',
                'furnishing' => 'Semi Furnished',
                'water_source' => 'PDAM',
                'garage_size' => 4,
                'carport_size' => 2,
                'is_hook' => false,
                'has_canopy' => true,
                'has_smart_home' => true,
                'has_fence' => false,
                'has_pool' => true,
                'has_carport' => true,
                'has_garden' => true,
                'city' => 'Surabaya',
                'district' => 'Wiyung',
                'address' => 'Graha Famili Blok K',
                'photo' => 'https://images.unsplash.com/photo-1600596542815-e32c2159f828?q=80&w=1200&auto=format&fit=crop',
                'gallery' => ['https://images.unsplash.com/photo-1600607687644-c7171b42498f?q=80&w=1200'],
            ],

            // --- KATEGORI: RUMAH MENENGAH (MIDDLE-UP) ---
            [
                'title' => 'Rumah Baru Gress di Wisata Bukit Mas',
                'description' => "Rumah baru gress minimalis modern. Lokasi depan taman, row jalan lebar 3 mobil. Siap huni.",
                'price' => 3200000000,
                'listing_type' => 'primary',
                'property_type' => 'rumah',
                'bedrooms' => 3,
                'maid_bedrooms' => 1,
                'bathrooms' => 3,
                'maid_bathrooms' => 1,
                'land_area' => 120,
                'building_area' => 180,
                'floor_count' => 2,
                'certificate' => 'HGB',
                'electricity' => 4400,
                'orientation' => 'Selatan',
                'furnishing' => 'Unfurnished',
                'water_source' => 'PDAM',
                'garage_size' => 0,
                'carport_size' => 2,
                'is_hook' => false,
                'has_canopy' => true,
                'has_smart_home' => false,
                'has_fence' => true,
                'has_pool' => false,
                'has_carport' => true,
                'has_garden' => true,
                'city' => 'Surabaya',
                'district' => 'Lakarsantri',
                'address' => 'Wisata Bukit Mas 2',
                'photo' => 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1200&auto=format&fit=crop',
                'gallery' => ['https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=1200'],
            ],
            [
                'title' => 'Rumah Minimalis Siap Huni Rungkut',
                'description' => "Rumah terawat di Rungkut Asri. Dekat UPN dan MERR. Cocok untuk keluarga muda.",
                'price' => 1250000000,
                'listing_type' => 'secondary',
                'property_type' => 'rumah',
                'bedrooms' => 3,
                'maid_bedrooms' => 0,
                'bathrooms' => 2,
                'maid_bathrooms' => 0,
                'land_area' => 100,
                'building_area' => 90,
                'floor_count' => 1,
                'certificate' => 'SHM',
                'electricity' => 2200,
                'orientation' => 'Barat',
                'furnishing' => 'Semi Furnished',
                'water_source' => 'PDAM',
                'garage_size' => 0,
                'carport_size' => 1,
                'is_hook' => false,
                'has_canopy' => true,
                'has_smart_home' => false,
                'has_fence' => true,
                'has_pool' => false,
                'has_carport' => true,
                'has_garden' => false,
                'city' => 'Surabaya',
                'district' => 'Rungkut',
                'address' => 'Rungkut Asri Tengah',
                'photo' => 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f8e?q=80&w=1200&auto=format&fit=crop',
                'gallery' => [],
            ],

            // --- KATEGORI: RUMAH SUBSIDI / MILENIAL (< 1M) ---
            [
                'title' => 'Rumah Murah di Gunung Anyar',
                'description' => "Rumah sederhana harga terjangkau di Surabaya Timur. Dekat OERR (Jalan Lingkar Luar Timur). Bebas banjir.",
                'price' => 650000000,
                'listing_type' => 'secondary',
                'property_type' => 'rumah',
                'bedrooms' => 2,
                'maid_bedrooms' => 0,
                'bathrooms' => 1,
                'maid_bathrooms' => 0,
                'land_area' => 72,
                'building_area' => 45,
                'floor_count' => 1,
                'certificate' => 'SHM',
                'electricity' => 1300,
                'orientation' => 'Utara',
                'furnishing' => 'Unfurnished',
                'water_source' => 'PDAM',
                'garage_size' => 0,
                'carport_size' => 1,
                'is_hook' => false,
                'has_canopy' => false,
                'has_smart_home' => false,
                'has_fence' => true,
                'has_pool' => false,
                'has_carport' => true,
                'has_garden' => false,
                'city' => 'Surabaya',
                'district' => 'Gunung Anyar',
                'address' => 'Gunung Anyar Tambak',
                'photo' => 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?q=80&w=1200&auto=format&fit=crop',
                'gallery' => [],
            ],

            // --- KATEGORI: APARTEMEN ---
            [
                'title' => 'Apartemen Ciputra World 2BR View City',
                'description' => 'Apartemen premium di atas Mall Ciputra World. Akses langsung mall. Full Furnished interior mewah.',
                'price' => 1800000000,
                'listing_type' => 'secondary',
                'property_type' => 'apartemen',
                'bedrooms' => 2,
                'maid_bedrooms' => 0,
                'bathrooms' => 1,
                'maid_bathrooms' => 0,
                'land_area' => 0,
                'building_area' => 64,
                'floor_count' => 30,
                'certificate' => 'Strata Title',
                'electricity' => 3500,
                'orientation' => 'Timur',
                'furnishing' => 'Full Furnished',
                'water_source' => 'PDAM',
                'garage_size' => 0,
                'carport_size' => 0,
                'is_hook' => false,
                'has_canopy' => false,
                'has_smart_home' => true,
                'has_fence' => false,
                'has_pool' => true,
                'has_carport' => false,
                'has_garden' => false,
                'city' => 'Surabaya',
                'district' => 'Dukuh Pakis',
                'address' => 'The Via & Vue Towers',
                'photo' => 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200&auto=format&fit=crop',
                'gallery' => ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200'],
            ],
            [
                'title' => 'Apartemen Puncak Benson Studio Murah',
                'description' => 'Jual rugi unit studio di Puncak Benson Pakuwon. View pool. Cocok untuk mahasiswa unesa/pakuwon.',
                'price' => 350000000,
                'listing_type' => 'secondary',
                'property_type' => 'apartemen',
                'bedrooms' => 1,
                'maid_bedrooms' => 0,
                'bathrooms' => 1,
                'maid_bathrooms' => 0,
                'land_area' => 0,
                'building_area' => 21,
                'floor_count' => 15,
                'certificate' => 'Strata Title',
                'electricity' => 1300,
                'orientation' => 'Barat',
                'furnishing' => 'Unfurnished',
                'water_source' => 'PDAM',
                'garage_size' => 0,
                'carport_size' => 0,
                'is_hook' => false,
                'has_canopy' => false,
                'has_smart_home' => false,
                'has_fence' => false,
                'has_pool' => true,
                'has_carport' => false,
                'has_garden' => false,
                'city' => 'Surabaya',
                'district' => 'Wiyung',
                'address' => 'Puncak Benson Lontar',
                'photo' => 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200&auto=format&fit=crop',
                'gallery' => [],
            ],

            // --- KATEGORI: RUKO & KOMERSIAL ---
            [
                'title' => 'Ruko 3 Lantai Nol Jalan MERR',
                'description' => "Ruko strategis di jalan utama MERR. Area parkir luas. Cocok untuk Bank, Klinik, atau Kantor.",
                'price' => 3500000000,
                'listing_type' => 'primary',
                'property_type' => 'ruko',
                'bedrooms' => 0,
                'maid_bedrooms' => 0,
                'bathrooms' => 3,
                'maid_bathrooms' => 0,
                'land_area' => 67,
                'building_area' => 200,
                'floor_count' => 3,
                'certificate' => 'HGB',
                'electricity' => 5500,
                'orientation' => 'Timur',
                'furnishing' => 'Unfurnished',
                'water_source' => 'PDAM',
                'garage_size' => 0,
                'carport_size' => 4,
                'is_hook' => false,
                'has_canopy' => false,
                'has_smart_home' => false,
                'has_fence' => false,
                'has_pool' => false,
                'has_carport' => true,
                'has_garden' => false,
                'city' => 'Surabaya',
                'district' => 'Sukolilo',
                'address' => 'Jl. Dr. Ir. H. Soekarno',
                'photo' => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
                'gallery' => ['https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200'],
            ],
            [
                'title' => 'Ruko HR Muhammad 4 Lantai',
                'description' => "Ruko premium di kawasan bisnis HR Muhammad Surabaya Barat. Lift Ready. Kondisi terawat.",
                'price' => 8000000000,
                'listing_type' => 'secondary',
                'property_type' => 'ruko',
                'bedrooms' => 0,
                'maid_bedrooms' => 0,
                'bathrooms' => 4,
                'maid_bathrooms' => 0,
                'land_area' => 100,
                'building_area' => 350,
                'floor_count' => 4,
                'certificate' => 'SHM',
                'electricity' => 11000,
                'orientation' => 'Selatan',
                'furnishing' => 'Semi Furnished',
                'water_source' => 'PDAM',
                'garage_size' => 0,
                'carport_size' => 2,
                'is_hook' => false,
                'has_canopy' => true,
                'has_smart_home' => true,
                'has_fence' => true,
                'has_pool' => false,
                'has_carport' => true,
                'has_garden' => false,
                'city' => 'Surabaya',
                'district' => 'Dukuh Pakis',
                'address' => 'Jl. HR Muhammad',
                'photo' => 'https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?q=80&w=1200&auto=format&fit=crop',
                'gallery' => [],
            ],

            // --- KATEGORI: TANAH / KAVLING ---
            [
                'title' => 'Tanah Kavling Siap Bangun Graha Famili',
                'description' => "Tanah kavling posisi premium di dalam cluster elite. Bentuk kotak presisi. Hadap Utara.",
                'price' => 15000000000,
                'listing_type' => 'secondary',
                'property_type' => 'tanah',
                'bedrooms' => 0,
                'maid_bedrooms' => 0,
                'bathrooms' => 0,
                'maid_bathrooms' => 0,
                'land_area' => 600,
                'building_area' => 0,
                'floor_count' => 0,
                'certificate' => 'SHM',
                'electricity' => 0,
                'orientation' => 'Utara',
                'furnishing' => 'Unfurnished',
                'water_source' => 'PDAM',
                'garage_size' => 0,
                'carport_size' => 0,
                'is_hook' => false,
                'has_canopy' => false,
                'has_smart_home' => false,
                'has_fence' => false,
                'has_pool' => false,
                'has_carport' => false,
                'has_garden' => false,
                'city' => 'Surabaya',
                'district' => 'Wiyung',
                'address' => 'Graha Famili Blok Z',
                'photo' => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1200&auto=format&fit=crop',
                'gallery' => [],
            ],
            [
                'title' => 'Tanah Komersial Jalan Raya Darmo',
                'description' => "Tanah langka di jalan protokol raya darmo. Cocok untuk gedung kantor atau hotel. Ijin komersial.",
                'price' => 50000000000,
                'listing_type' => 'secondary',
                'property_type' => 'tanah',
                'bedrooms' => 0,
                'maid_bedrooms' => 0,
                'bathrooms' => 0,
                'maid_bathrooms' => 0,
                'land_area' => 1000,
                'building_area' => 0,
                'floor_count' => 0,
                'certificate' => 'SHM',
                'electricity' => 0,
                'orientation' => 'Barat',
                'furnishing' => 'Unfurnished',
                'water_source' => 'PDAM',
                'garage_size' => 0,
                'carport_size' => 0,
                'is_hook' => false,
                'has_canopy' => false,
                'has_smart_home' => false,
                'has_fence' => false,
                'has_pool' => false,
                'has_carport' => false,
                'has_garden' => false,
                'city' => 'Surabaya',
                'district' => 'Tegalsari',
                'address' => 'Jl. Raya Darmo',
                'photo' => 'https://images.unsplash.com/photo-1524813686514-a57563d77965?q=80&w=1200&auto=format&fit=crop',
                'gallery' => [],
            ],
            [
                'title' => 'Gudang Margomulyo Indah Siap Pakai',
                'description' => "Gudang siap pakai di kawasan industri Margomulyo. Akses kontainer 40 feet. Bebas banjir.",
                'price' => 8500000000,
                'listing_type' => 'secondary',
                'property_type' => 'gudang',
                'bedrooms' => 0,
                'maid_bedrooms' => 0,
                'bathrooms' => 2,
                'maid_bathrooms' => 0,
                'land_area' => 500,
                'building_area' => 400,
                'floor_count' => 1,
                'certificate' => 'HGB',
                'electricity' => 23000,
                'orientation' => 'Selatan',
                'furnishing' => 'Unfurnished',
                'water_source' => 'PDAM',
                'garage_size' => 0,
                'carport_size' => 5,
                'is_hook' => false,
                'has_canopy' => true,
                'has_smart_home' => false,
                'has_fence' => true,
                'has_pool' => false,
                'has_carport' => true,
                'has_garden' => false,
                'city' => 'Surabaya',
                'district' => 'Tandes',
                'address' => 'Kawasan Industri Margomulyo',
                'photo' => 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=1200&auto=format&fit=crop',
                'gallery' => [],
            ],
        ];

        foreach ($properties as $prop) {
            Property::create(array_merge($prop, [
                'user_id' => $user->id,
                'slug' => Str::slug($prop['title']) . '-' . rand(1000, 9999),
                'is_active' => true,
            ]));
        }
    }
}
